# Let's Chat: Docker Compose
# https://docs.docker.com/compose/
#
# Usage: docker-compose up

app:
  image: letschat:latest
  links:
    - mongo
  ports:
    - 80:8080
    - 5222:5222
  environment :
   - MONGO_DOCKER = mongodb://192.168.99.100:27017/hp_mongo
  # - DEBUGGER  = "--debug-brk"
mongo:
  image: mongo:latest
  ports :
    - 27017:27017
